---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths: ['lib']
