language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4"
addons:
    code_climate:
        repo_token: 6775ee86a715a8a1b9371e95eed5353c2d2620ffb48ba7aa2094d481dd361b48
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
